name: default
create_nuggets: false
create_qrels: true
judge: true
llm_model: dummy
timestamp: '2026-02-04T00:56:56.622641+00:00'
git:
  commit: 1a3fc0c05b0cbc5b9c7e522cd70c6173cb2803ba
  dirty: 'true'
  remote: https://github.com/laura-dietz/auto-judge-code-test.git
judge_settings:
  length_weight: 0.2
  keyword_weight: 0.3
  bm25_weight: 0.3
  coverage_weight: 0.2
  min_length: 50
  optimal_length: 200
  max_length: 500
